name: istream
description: An app to that has infinite possibilities
publish_to: 'https://github.com/kazemcodes/IStream'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.7.2'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  get: ^4.6.5
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true
